app = "portfolio-ssh-63su5w"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "2222"

[[services]]
  protocol = "tcp"
  internal_port = 2222
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 22
